language: java
jdk:
    - openjdk8

env:
    - TERM=dumb

before_install:
    - chmod +x gradlew

script:
    - ./gradlew jar

after_success:
    - ./gradlew jacocoTestReport coveralls

sudo: false

cache:
    directories:
        - $HOME/.gradle
